config/routes.rb
Rails.application.routes.draw do

  
  resources :blocked_users
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles do
    resources :comments
    get 'admin_comments', to: "comments#admin_index"
  end
  
  get 'signup', to:'users#new'
  
  resources :users
  resources :friendships
    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  resources :categories, except: [:destroy]
  
  

end

app/models/blocked_user.rb
class BlockedUser < ActiveRecord::Base
  belongs_to :users
   belongs_to :blocked_user, :class_name => "User"
end

app/controllers/blocked_users_controller.rb
class BlockedUsersController < ApplicationController
  before_action :set_blocked_user, only: [:show, :edit, :update, :destroy]

  # GET /blocked_users
  # GET /blocked_users.json
  def index
    @blocked_users = BlockedUser.all
    @user = current_user
  end

  # GET /blocked_users/1
  # GET /blocked_users/1.json
  def show
  end

  # GET /blocked_users/new
  def new
    @blocked_user = BlockedUser.new
  end

  # GET /blocked_users/1/edit
  def edit
  end

  # POST /blocked_users
  # POST /blocked_users.json
  def create
      @user = User.find(params[:blocked_id])
      @blocked_user = current_user.blocked_users.build( user_id: current_user.id, blocked_id: @user.id, blocked_username: @user.username)
      if @blocked_user.save
        flash[:success] = "#{@blocked_user.blocked_username} has been blocked."
        redirect_to :back
      else
        flash[:danger] = "Unable to block user."
        redirect_to :back
      end
  end
  # PATCH/PUT /blocked_users/1
  # PATCH/PUT /blocked_users/1.json
  #def update
  #  respond_to do |format|
  #    if @blocked_user.update(blocked_user_params)
  #      format.html { redirect_to @blocked_user, notice: 'Blocked user was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @blocked_user }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @blocked_user.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /blocked_users/1
  # DELETE /blocked_users/1.json
  def destroy
    @blocked_user.destroy
    respond_to do |format|
      format.html { redirect_to blocked_users_url, success: "#{@blocked_user.blocked_username} has been unblocked." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blocked_user
      @blocked_user = BlockedUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blocked_user_params
      params.require(:blocked_user).permit(:user_id, :blocked_id)
    end
end

app/helpers/blocked_users_helper.rb
module BlockedUsersHelper
end

app/views/blocked_users/_form.html.erb
<%= form_for(@blocked_user) do |f| %>
  <% if @blocked_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blocked_user.errors.count, "error") %> prohibited this blocked_user from being saved:</h2>

      <ul>
      <% @blocked_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :blocked_id %><br>
    <%= f.number_field :blocked_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocked_users/edit.html.erb
<h1>Editing Blocked User</h1>

<%= render 'form' %>

<%= link_to 'Show', @blocked_user %> |
<%= link_to 'Back', blocked_users_path %>

app/views/blocked_users/index.html.erb
<div align="center">
  <div>
    <%= link_to gravatar_for(@user), user_path(@user) %>
  </div>
  <p id="notice"><%= notice %></p>

  <h1>Listing <%= current_user.username %>'s Blocked Users</h1>
  
  <table>
    <thead>
      <tr>
        <th>Blocked Users</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @blocked_users.each do |blocked_user| %>
        <tr>
  
          <td><%= blocked_user.blocked_username %></td>
          <td><%= link_to 'Unblock', blocked_user, method: :delete, data: { confirm: "Are you sure you want to unblock #{blocked_user.blocked_username}?" }, class: "btn btn-xs btn-info" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/blocked_users/new.html.erb
<h1>New Blocked User</h1>

<%= render 'form' %>

<%= link_to 'Back', blocked_users_path %>

app/views/blocked_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blocked_user.user_id %>
</p>

<p>
  <strong>Blocked:</strong>
  <%= @blocked_user.blocked_id %>
</p>

<%= link_to 'Edit', edit_blocked_user_path(@blocked_user) %> |
<%= link_to 'Back', blocked_users_path %>